Repository owncloud/market, pull requests merged in 2019-02, with the labels that each got.

#448 Fix typo "Logged In"
  src/components/Login.vue
Labels: 3 - To Review

#450 Fix "Logged In" is shown despite being logged out
  src/components/Login.vue
Labels: 4 - To release

#185 Hide 'Edit/Add API Key' button if not changeable
  src/components/ApiForm.vue
Labels: enhancement

#145 prevent uninstalling market app from within market app
  lib/MarketService.php
  src/components/Details.vue
  tests/unit/MarketServiceTest.php
Labels: 3 - To Review

#454 Hide api key in xhr-responses if key is configured in config.php
  lib/Controller/LocalAppsController.php
  lib/Controller/MarketController.php
  tests/unit/MarketControllerTest.php
Labels: 2 - Developing, bug
