Repository owncloud/market, pull requests merged in 2020-04, with the labels that each got.

#545 Bump PHP dependencies
  composer.lock
Labels: 3 - To Review, dependencies, php

#551 [Tests-Only] Update phpstan to latest version
  .drone.star
  lib/CheckUpdateBackgroundJob.php
  lib/Command/InstallApp.php
  lib/Command/ListApps.php
  lib/Command/UnInstallApp.php
  lib/Command/UpgradeApp.php
  lib/Controller/MarketController.php
  lib/HttpService.php
  lib/MarketService.php
  lib/Notifier.php
  lib/VersionHelper.php
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 4 - To release

#552 [Tests-Only] Bump phan 2.7
  vendor-bin/phan/composer.json
Labels: QA-team

#555 [Tests-Only] Implement PHPUnit v8
  .gitignore
  tests/unit/Command/InstallAppTest.php
  tests/unit/Command/ListAppsTest.php
  tests/unit/Command/UnInstallAppTest.php
  tests/unit/Command/UpgradeAppTest.php
Labels: 3 - To Review, QA-team

#557 Adjust drone pipelines for PHP 7.4
  .drone.star
Labels: 3 - To Review, QA-team
